server:
  port: 3001
  context-path: /
spring:
  application:
    name: zuul
eureka:
  instance:
    instance-id: zuul:3001
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka2001.wyy.com:2001/eureka/,http://eureka2002.wyy.com:2002/eureka/,http://eureka2003.wyy.com:2003/eureka/
info:
  groupId: com.wyy.springcloud_p2p
  artifactId: zuul_3001_p2p
  version: 1.0-SNAPSHOT
  userName: http://wyy.com
  phone: 123456





